version: "3.9"

services:
  postgres:
    container_name: gofinance-db
    image: postgres:12
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gofinance-network

  backend:
    container_name: gofinance-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - gofinance-network
    volumes:
      - ./backend:/backend

  frontend:
    container_name: gofinance-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    networks:
      - gofinance-network
      

volumes:
  pgdata: {}

networks:
  gofinance-network:
    driver: bridge
